{"name": "Заказы пользователя из раздела «История заказов» отображаются на странице «Лента заказов»", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <tests.test_order_feed_page.TestOrderFeedPage object at 0x0000029FDE977EE0>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"75a29aee75cf2756682462fa2bd295c2\")>\n\n    @allure.title('Заказы пользователя из раздела «История заказов» отображаются на странице «Лента заказов»')\n    def test_order_user_history_and_order_feed(self, driver):\n>       num_order = OrderFeedPage(driver).base_check_order_user_history_and_order_feed()\n\ntests\\test_order_feed_page.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\order_feed_page.py:198: in base_check_order_user_history_and_order_feed\n    number_order = self.base_check_number_new_order()\npages\\order_feed_page.py:185: in base_check_number_new_order\n    self.wait__element_number_orders()\npages\\order_feed_page.py:53: in wait__element_number_orders\n    return self.wait_element_(locator, text_value)\npages\\base_page.py:43: in wait_element_\n    return WebDriverWait(self.driver, 15).until(expected_conditions.none_of(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"75a29aee75cf2756682462fa2bd295c2\")>, method = <function none_of.<locals>.none_of_condition at 0x0000029FDE995D80>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nvenv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "steps": [{"name": "Общие шаги: заказы пользователя из раздела \"История заказов\" отображаются на странице \"Лента заказов\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\order_feed_page.py\", line 198, in base_check_order_user_history_and_order_feed\n    number_order = self.base_check_number_new_order()\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\order_feed_page.py\", line 185, in base_check_number_new_order\n    self.wait__element_number_orders()\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\order_feed_page.py\", line 53, in wait__element_number_orders\n    return self.wait_element_(locator, text_value)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\base_page.py\", line 43, in wait_element_\n    return WebDriverWait(self.driver, 15).until(expected_conditions.none_of(\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Общие шаги получения номера нового заказа", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\order_feed_page.py\", line 185, in base_check_number_new_order\n    self.wait__element_number_orders()\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\order_feed_page.py\", line 53, in wait__element_number_orders\n    return self.wait_element_(locator, text_value)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\base_page.py\", line 43, in wait_element_\n    return WebDriverWait(self.driver, 15).until(expected_conditions.none_of(\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Общие шаги для авторизации", "status": "passed", "steps": [{"name": "Ожидаем кликабельность кнопки \"Войти в аккаунт\"", "status": "passed", "start": 1704921484433, "stop": 1704921484459}, {"name": "Нажимаем на кнопку \"Войти в аккаунт\" на главной странице", "status": "passed", "start": 1704921484459, "stop": 1704921484586}, {"name": "Нажимаем на поле \"Email\" на странице авторизации", "status": "passed", "start": 1704921484589, "stop": 1704921484643}, {"name": "Вводим email зарегистрированного пользователя на странице авторизации", "status": "passed", "start": 1704921484643, "stop": 1704921484704}, {"name": "Нажимаем на поле \"Пароль\" на странице авторизации", "status": "passed", "start": 1704921484704, "stop": 1704921484757}, {"name": "Вводим пароль зарегистрированного пользователя на странице авторизации", "status": "passed", "start": 1704921484757, "stop": 1704921484797}, {"name": "Ожидаем кнопку \"Войти\" на странице авторизации", "status": "passed", "start": 1704921484797, "stop": 1704921484815}, {"name": "Нажимаем на кнопку \"Войти\" на странице авторизации", "status": "passed", "start": 1704921484815, "stop": 1704921484852}], "start": 1704921484423, "stop": 1704921484855}, {"name": "Перетаскиваем ингредиент в заказ", "status": "passed", "start": 1704921484855, "stop": 1704921485983}, {"name": "Нажимаем на кнопку \"Оформить заказ\"", "status": "passed", "start": 1704921485983, "stop": 1704921486033}, {"name": "Ожидание появления нового номера заказов", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\order_feed_page.py\", line 53, in wait__element_number_orders\n    return self.wait_element_(locator, text_value)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\base_page.py\", line 43, in wait_element_\n    return WebDriverWait(self.driver, 15).until(expected_conditions.none_of(\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1704921486036, "stop": 1704921501528}], "start": 1704921484423, "stop": 1704921501531}], "start": 1704921484423, "stop": 1704921501531}], "start": 1704921484423, "stop": 1704921501532, "uuid": "2f839dc3-ba6e-4d23-949f-2b2b91cebaee", "historyId": "07b1a82eda63055fd8a5648116a3fd46", "testCaseId": "07b1a82eda63055fd8a5648116a3fd46", "fullName": "tests.test_order_feed_page.TestOrderFeedPage#test_order_user_history_and_order_feed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_feed_page"}, {"name": "subSuite", "value": "TestOrderFeedPage"}, {"name": "host", "value": "LAPTOP-588797DN"}, {"name": "thread", "value": "35284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_feed_page"}]}